= Contributing to the Spring Framework

First off, thank you for taking the time to contribute! :+1: :tada:

== Table of Contents

* <<code-of-conduct>>
* <<how-to-contribute>>
* <<report-security-vulnerabilities>>
* <<discuss>>
* <<create-an-issue>>
* <<issue-lifecycle>>
* <<build-from-source>>
* <<use-code-style>>
* <<submit-a-pull-request>>

[[code-of-conduct]]
== Code of Conduct

This project is governed by the https://github.com/spring-projects/.github/blob/main/CODE_OF_CONDUCT.md[Spring Code of Conduct].
By participating you are expected to uphold this code.
Please report unacceptable behavior to pvtl-spring-code-of-conduct@vmware.com.

[[how-to-contribute]]
== How to Contribute

[[report-security-vulnerabilities]]
=== Report Security Vulnerabilities
If you think you have found a security vulnerability in Spring Security please DO NOT disclose it publicly until we’ve had a chance to fix it.
Please don’t report security vulnerabilities using GitHub issues, instead head over to https://spring.io/security-policy to disclose them responsibly.

[[discuss]]
=== Discuss

If you have a question, check Stack Overflow using
https://stackoverflow.com/questions/tagged/spring-security?tab=Newest[the `spring-security` tag].
Find an existing discussion, or start a new one if necessary.

If you believe there is an issue, search through https://github.com/spring-projects/spring-framework/issues[existing issues] trying a few different ways to find discussions, past or current, that are related to the issue.
Reading those discussions helps you to learn about the issue, and helps us to make a decision.

[[create-an-issue]]
=== Create an Issue

Reporting an issue or making a feature request is a great way to contribute.
Your feedback and the conversations that result from it provide a continuous flow of ideas.
However, before creating a ticket, please take the time to <<discuss,discuss and research>> first.

If creating an issue after a discussion on Stack Overflow, please provide a description in the issue instead of simply referring to Stack Overflow.
The issue tracker is an important place of record for design discussions and should be self-sufficient.

Once you're ready, create an issue on https://github.com/spring-projects/spring-security/issues[GitHub].

[[issue-lifecycle]]
==== Issue Lifecycle

When an issue is first created, it is flagged `waiting-for-triage` waiting for a team member to triage it.
Once the issue has been reviewed, the team may ask for further information if needed, and based on the findings, the issue is either assigned a target milestone or is closed with a specific status.

When a fix is ready, the issue is closed and may still be re-opened until the fix is released.
After that the issue will typically no longer be reopened.
In rare cases if the issue was not at all fixed, the issue may be re-opened.
In most cases however any follow-up reports will need to be created as new issues with a fresh description.

=== Participate in Reviews

Helping to review pull requests is another great way to contribute.
Your feedback can help to shape the implementation of new features.
When reviewing pull requests, however, please refrain from approving or rejecting a PR unless you are a core committer to Spring Security.

[[build-from-source]]
=== Build from Source

This document describes how to build Spring Security from the command line and how to import the project into an IDE.
You may also be interested to see https://github.com/spring-projects/spring-framework/wiki/Code-Style[Code Style] and https://github.com/spring-projects/spring-framework/wiki/IntelliJ-IDEA-Editor-Settings[IntelliJ IDEA Editor Settings].

Spring Security uses a https://gradle.org[Gradle] build.
The instructions below use the https://vimeo.com/34436402[Gradle Wrapper] from the root of the source tree.
The wrapper script serves as a cross-platform, self-contained bootstrap mechanism for the build system.

==== Prepare Your Environment
To build you will need https://help.github.com/set-up-git-redirect[Git] and https://adoptopenjdk.net/[JDK 11].
Be sure that your JAVA_HOME environment variable points to the jdk11 folder extracted from the JDK download.

==== Get the Source Code
[source,bash]
----
git clone git@github.com:spring-projects/spring-security.git
cd spring-security
----

==== Build from the Command Line
To compile, test, and build all jars, distribution zips, and docs use:

[source,bash]
----
./gradlew format check
----

The first time you run the build it may take a while to download Gradle and all build dependencies, as well as to run all tests.
Once you've bootstrapped a Gradle distribution and downloaded dependencies, those are cached in your `$HOME/.gradle` directory.

Gradle has good incremental build support, so run without clean to keep things snappy.
You can also use the `-a` flag and the `:project` prefix to avoid evaluating and building other modules.
For example, if iterating over changes in `spring-security-ldap`, run with the following to evaluate and build only that module:

[source,bash]
----
./gradlew -a :spring-security-ldap:test
----

==== Import into your IDE

Ensure JDK 11 is configured properly in the IDE.
Follow instructions for https://github.com/spring-projects/spring-framework/blob/master/import-into-eclipse.md[Eclipse] and https://github.com/spring-projects/spring-framework/blob/master/import-into-idea.md[IntelliJ IDEA].

[[use-code-style]]
=== Use Code Style

The https://github.com/spring-io/spring-javaformat/[Spring JavaFormat] plugin addresses all whitespace requirements when you call the `format` Gradle task.

We additionally follow https://github.com/spring-projects/spring-framework/wiki/Code-Style[Spring Framework's Code Style] guidelines.
If you are using IntelliJ, the following https://github.com/spring-projects/spring-framework/wiki/IntelliJ-IDEA-Editor-Settings[editor settings] can help with code style.

[[submit-a-pull-request]]
=== Submit a Pull Request

1. If you have not previously done so, please sign the https://cla.pivotal.io/sign/spring[Contributor License Agreement].
You will be reminded automatically when you submit the PR.

2. Must you create an issue first?
No, you can begin with a pull request and use the description to provide context and motivation, as you would for an issue.
If discussion is needed, please create an issue as we prefer to keep discussions there.

3. Always check out the `main` branch, create a topic branch from it, and submit pull requests against that topic branch (for target version see [settings.gradle](settings.gradle)).
If there is a related issue, it's helpful to name the branch `gh-{issuenumber}`.
Backports to prior versions will be considered on a case-by-case basis and reflected as the fix version in the issue tracker.

4. Add https://github.com/spring-projects/spring-framework/wiki/Code-Style#tests[unit tests].
For new features, the unit tests should demonstrate the feature working.
For bugs, the unit test should fail before your fix and pass after your fix.

5. Choose the granularity of your commits consciously and squash commits that represent multiple edits or corrections of the same logical change.
See https://git-scm.com/book/en/Git-Tools-Rewriting-History[Rewriting History section of Pro Git] for an overview of streamlining the commit history.

6. Format commit messages using 55 characters for the subject line, 72 characters per line for the description, followed by the issue fixed, for example, `Closes gh-22276`.
See the https://git-scm.com/book/en/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines[Commit Guidelines section of Pro Git] for best practices around commit messages, and use `git log` to see some examples.

7. If there is a related issue, reference the GitHub issue number in the description of the pull request.

If accepted, your contribution may be heavily modified as needed prior to merging.
You will likely retain author attribution for your Git commits granted that the bulk of your changes remain intact.
You may also be asked to rework the submission.

If asked to make corrections, simply push the changes against the same branch, and your pull request will be updated.
In other words, you do not need to create a new pull request when asked to make changes.

[[additional-tips]]
=== Additional Tips

* If you are updating the schema, update `spring-security-x.y.z.rnc` instead of `spring-security-x.y.z.xsd`.
The task `./gradlew rncToXsd` will update the XSD for you.
