[[password-mgmt]]
== Password Management
Any system that stores the user's password will need a way to manage it.

=== Change Password Page Discovery
Various password management tools exist that a user can use to keep track of their passwords.
Using a well-known change password endpoint https://wicg.github.io/change-password-url/[can help these password tools], so that they or the user can easily rotate their passwords from one location.

You can tell Spring Security to stand up a standard redirect filter that uses a well-known endpoint, like so:

.Password Management Configuration
====
.Java
[source,java,role="primary"]
-----
http
    ...
    .passwordManagement(pass -> {});
-----

.Kotlin
[source,kotlin,role="secondary"]
-----
http {
    ...
    passwordManagement { }
}
-----

.Xml
[source,xml,role="tertiary"]
-----
<http>
...
<password-management/>
</http>
-----
====

Now, when a password management tool requests the `/.well-known/change-password` endpoint, it will be redirected to `/change-password` in the application.

NOTE: Spring Security doesn't provide a default change password page at this time.
You will need to provide the `/change-password` endpoint.

Likely, you've already got your own change password endpoint, and so you can also configure Spring Security with whatever that's named, as can be seen below:

.Password Management Configuration
====
.Java
[source,java,role="primary"]
-----
http
    ...
    .passwordManagement(pass -> pass
        .changePasswordPage("/passwordChange.htm")
    );
-----

.Kotlin
[source,kotlin,role="secondary"]
-----
http {
    ...
    passwordManagement {
        changePasswordPage = "/passwordChange.htm"
    }
}
-----

.Xml
[source,xml,role="tertiary"]
-----
<http>
...
<password-management change-password-page="/passwordChange.htm"/>
</http>
-----
====

With the above configuration, Spring Security will redirect `/.well-known/change-password` requests to `/passwordChange.htm`.
