= OAuth 2.0 Resource Server Sample

This sample demonstrates integrating Resource Server with a mock Authorization Server, though it can be modified to integrate
with your favorite Authorization Server.

With it, you can run the integration tests or run the application as a stand-alone service to explore how you can
secure your own service with OAuth 2.0 Bearer Tokens using Spring Security.

== 1. Running the tests

To run the tests, do:

```bash
./gradlew integrationTest
```

Or import the project into your IDE and run `OAuth2ResourceServerApplicationTests` from there.

=== What is it doing?

By default, the tests are pointing at a mock Authorization Server instance.

The tests are configured with a set of hard-coded tokens originally obtained from the mock Authorization Server,
and each makes a query to the Resource Server with their corresponding token.

The Resource Server subsquently verifies with the Authorization Server and authorizes the request, returning the phrase

```bash
Hello, {subject}!
```

where "subject" is the value of the `sub` field in the JWT returned by the Authorization Server.

== 2. Running the app

To run as a stand-alone application, do:

```bash
./gradlew bootRun
```

Or import the project into your IDE and run `OAuth2ResourceServerApplication` from there.

Once it is up, you can retreive a valid JWT token from the authorization server, and then hit the endpoint:

```bash
curl -H "Authorization: Bearer $TOKEN" localhost:8081
```

Which will respond with the phrase:

```bash
Hello, {subject}!
```

where `subject` is the value of the `sub` field in the JWT returned by the Authorization Server.

=== How do I obtain a valid JWT token?

Getting a valid JWT token from an Authorization Server will vary, depending on your setup. However, it will typically
look something like this:

```bash
curl --user $CLIENT_ID:$CLIENT_PWD -d "grant_type=client_credentials&scope=message:read" $AUTH_ENDPOINT/token
```

which will respond with a JSON payload containing the `access_token` among other things:

```json
{
  "access_token" : "{the access token}",
  "token_type" : "Bearer",
  "expires_in" : "{an expiry}",
  "scope" : "{a list of scopes}"
}
```

For example, the following can be used to hit the mock Authorization Server for a valid JWT token:

```bash
curl --user id:password -d "grant_type=client_credentials&scope=message:read" http://localhost:8082/token
```

Which will give a response similar to this (formatting mine):

```json
{
  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6Im1lc3NhZ2U6cmVhZCIsImV4cCI6MzEwNjMyODEzMSwianRpIjoiOGY5ZjFiYzItOWVlMi00NTJkLThhMGEtODg3YmE4YmViYjYzIn0.CM_KulSsIrNXW1x6NFeN5VwKQiIW-LIAScJzakRFDox8Ql7o4WOb0ubY3CjWYnglwqYzBvH9McCFqVrUtzdfODY5tyEEJSxWndIGExOi2osrwRPsY3AGzNa23GMfC9I03BFP1IFCq4ZfL-L6yVcIjLke-rA40UG-r-oA7r-N_zsLc5poO7Azf29IQgQF0GSRp4AKQprYHF5Q-Nz9XkILMDz9CwPQ9cbdLCC9smvaGmEAjMUr-C1QgM-_ulb42gWtRDLorW_eArg8g-fmIP0_w82eNWCBjLTy-WaDMACnDVrrUVsUMCqx6jS6h8_uejKly2NFuhyueIHZTTySqCZoTA",
  "token_type": "Bearer",
  "expires_in": 1576800000,
  "scope": "message:read"
}
```

Then, using that access token:

```bash
curl -H  "Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6Im1lc3NhZ2U6cmVhZCIsImV4cCI6MzEwNjMyODEzMSwianRpIjoiOGY5ZjFiYzItOWVlMi00NTJkLThhMGEtODg3YmE4YmViYjYzIn0.CM_KulSsIrNXW1x6NFeN5VwKQiIW-LIAScJzakRFDox8Ql7o4WOb0ubY3CjWYnglwqYzBvH9McCFqVrUtzdfODY5tyEEJSxWndIGExOi2osrwRPsY3AGzNa23GMfC9I03BFP1IFCq4ZfL-L6yVcIjLke-rA40UG-r-oA7r-N_zsLc5poO7Azf29IQgQF0GSRp4AKQprYHF5Q-Nz9XkILMDz9CwPQ9cbdLCC9smvaGmEAjMUr-C1QgM-_ulb42gWtRDLorW_eArg8g-fmIP0_w82eNWCBjLTy-WaDMACnDVrrUVsUMCqx6jS6h8_uejKly2NFuhyueIHZTTySqCZoTA" \
  localhost:8081
```

I get:

```bash
Hello, {subject}!
```

== 3. Testing against other Authorization Servers

To change the sample to point at your Authorization Server, simply find this section:

```yaml
spring:
  security:
    oauth2:
      resourceserver:
        issuer:
          mock:
            jwk-set-uri: http://localhost:8081/.well-known/jwks.json
```

And change `mock` to the name of your authorization server and `jwk-set-uri` to your authorization server's endpoint:

```yaml
spring:
  security:
    oauth2:
      resourceserver:
        issuer:
          okta:
            jwk-set-uri: https://dev-123456.oktapreview.com/oauth2/default/v1/keys
```

If your Authorization Server sends scopes using something other than the `scope` attribute, you can specify it as well:


```yaml
spring:
  security:
    oauth2:
      resourceserver:
        issuer:
          okta:
            jwk-set-uri: https://dev-123456.oktapreview.com/oauth2/default/v1/keys
            scope-attribute-name: scp
```

*(Note that the mock server will only turn on when it is explicitly configured or when there is no issuer configuration at all, meaning that with the above configuration, it will not turn on when the app is run)*

And then you can run the app the same as before:

```bash
./gradlew bootRun
```

Make sure to obtain valid tokens from your Authorization Server in order to play with the Resource Server.
To use the `/` endpoint, any valid token from your Authorization Server will do.
To use the `/message` endpoint, the token should have the `message:read` scope.

=== Can I run the integration tests against my Authorization Server?

If you want to run the integration tests against your Authorization Server, first follow the above steps.

Then you'll need to write the two tokens, one with the `message:read` scope and one without, into the `src/integration-test/resources` directory.

For example, you could:

1. POST to your Authorization Server's /token endpoint, once for `message:read`:

    curl \
        --user $CLIENT_ID:$CLIENT_PWD \
        -d "grant_type=client_credentials&scope=message:read" \
        $AUTH_ENDPOINT/token \
      | jq -r .access_token \
      > src/integration-test/resources/message-read.scope

2. And again for an unscoped token:

    curl \
        --user $CLIENT_ID:$CLIENT_PWD \
        -d "grant_type=client_credentials" \
        $AUTH_ENDPOINT/token \
      | jq -r .access_token \
      > src/integration-test/resources/no.scope


At that point, you will be able to run the integration tests against your Authorization Server.
